services:
  - type: web
    name: leap-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install --production=false && npx prisma generate && npm run build && ls -R dist
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "10000"

  - type: web
    name: leap-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: leap-backend
          property: host
